### ISSUE TITLE
Extreme performance difference between JS and C++ export.

### ISSUE THREAD

**Issue by 5Mixer** [snowkit/differ#22]
I've used differ very naively in my project, with every tilemap tile having it's own box collider, and with every collision check checking _all_ of these tiles. It's bad - and I'll fix it with a quad tree or something - but the JS export of my project has been working fine, not lagging at all. However, when I export for windows (I'm using Kha) the app can't run, and after just seconds will freeze and close. I think this performance difference is due to differ, as when running the windows build through visual studio, the performance tools reported that 81.53% of my builds CPU time was spent on a differ method.

![perf plz](https://cloud.githubusercontent.com/assets/8501694/21703100/bdecf644-d403-11e6-8134-aa1988283bea.png)

Feel free to close this if this is outside's of differs control. I totally get that this sort of performance _should_ be expected with what I am doing. I'm just almost curious about why JS does work well, when I expected C++ performance to be higher.

**Comment by underscorediscovery** [comment]
It's interesting profile, but some concrete amounts would help figure it out (i.e how many shapes are you testing against? 

I'd also like to know what version of hxcpp + haxe, since that's where I'll start guessing the difference lies, something in the generated code for the c++ output is doing something that hxcpp dislikes. 

It's either that, or you're using it without using it's ability to avoid allocations, which will throw tons of garbage into the GC and could be a significant source of cost. The API let's you preallocate the results set for a number of shapes, since your shape count is typically known at the time of testing (it has to be) then you can preallocate all the data and there will be no allocations internally. If you don't specify, it creates new objects for every result for every test etc which could add up for sure.

JS don't forget is the by product of tens of years of hyper focus on making it fast, it's scary fast at a lot of things. So while plain native (even with hxcpp overhead) is typically expected to be faster, don't underestimate just how much structured optimization takes place in js engines these days. In synthetic tests it can perform similar or sometimes faster than native code since it can run code as JIT etc. WIth a grain of salt - the point is that cases like this shouldn't surprise you at all since js engines are quite ridiculous even when strung into a browser loop.

**Comment by 5Mixer** [comment]
hxcpp: 3.4.2
haxe 3.4.0
differ: git

Thanks for the reply. I'm not quite sure about how to avoid allocations with differ, I've just been making shapes and then checking for their collision with `Collision.shapeWithShapes` etc. For the dynamic colliders (shapes attached to stuff that moves, like the player), I update the shapes position to match the entities collision as I do my physics. With my system, it's kind of hard to tell exactly how many collision checks are going on, but I can sort of guess/work it out.

Tilemap: 40x40, with maybe 250 being collidable with differ shapes (But this could be as low as 10 and still have issues)
Player: 1
Bullets: 0...200? (It lags well before 20)

Maybe I should just target the web heh.

**Comment by underscorediscovery** [comment]
10 definitely sounds like something weird.

> I'm not quite sure about how to avoid allocations with differ

If you notice the code for `Collision.shapeWithShapes` has a third optional parameter, `?into:Results<ShapeCollision>`. This is the results set that differ will populate with the collision results. If you don't give it an existing set to use, it will create one - every time you call it.

The usage then, to avoid it from doing that, is simply having one already:

```haxe
//in your class
var results: Results<ShapeCollision>;

//at init time - i.e when you create your "shapes" array:
results = new Results<ShapeCollision>(shapes.length);

//usage time
var collisions = Collision.shapeWithShapes(shape1, shapes, results);
for(collision in collisions) { 
 ///
}
```

Since the `results` variable was a class member, you only need to create it once, and you specify the number of results to preallocate. If there are not enough preallocated, it will add to the result set for you, so you don't need to know the total up front - but it will be more predictable allocation wise if you do.

The results is basically a container that pretends that it has less items than it does, which lets it update the results instances, acting like an array. 

All the calls in the library allow you to pass in a preallocated `into` variable - if you do, it won't allocate for every test that it performs, which should make a difference.

**Comment by 5Mixer** [comment]
Thanks for the reply! I've been side tracked by other game features but this issue is still kinda there, in the background.

I tried using the into argument, but with my current system it's tricky. I'm using ECS, which is odd enough to me, and collisions are a weird case where ECS kinda makes things trickier. I get a list of things that have physics and collide every frame, and that list might have different numbers of entities, some entities might collide with certain types of entities (I filter my collisions) and so on. Becomes a bit trickier than `shapes.length`. A big speed boost I found was, given I know all my collision boxes are currently 8x8, I just see if the pos of the two shapes are within ~16 pixels on the x and y axis. Most of my collision code is spent on the tilemap and this seemed to speed it up _slightly_. JS still vastly out performs cpp, no news there.

I'm interested in whether my old AABB collision checks are any faster, I'll have to check it out. Anyway, dunno if this is a differ issue so yeah feel free to close. Sorry for sloppy english I'm tired heh.

**Comment by RudenkoArts** [comment]
@5Mixer you can use spatialhash for broadphase collision detection, ive made some here [link](https://gist.github.com/RudenkoArts/2bc27bb7af9338699cda)

**Comment by 5Mixer** [comment]
Thanks I think I need to do some sort of broadphase thing. Code looks good but I might go with a quad tree I dunno my brain gets it easier.

**Comment by 5Mixer** [comment]
Closing. I was doing some stuff poorly and no broadphase. Thanks for help guys.
